# Generated by Django 5.1.3 on 2024-11-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModulPembelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('jumlah_soal', models.IntegerField()),
                ('waktu_pengajaran', models.IntegerField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul_pembelajaran', to='questify_app.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=255)),
                ('pilihan_b', models.CharField(max_length=255)),
                ('pilihan_c', models.CharField(max_length=255)),
                ('pilihan_d', models.CharField(max_length=255)),
                ('jawaban', models.CharField(max_length=1)),
                ('nilai_jawaban', models.IntegerField()),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='questify_app.modulpembelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='questify_app.kelas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='questify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembelian', to='questify_app.kelas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembelian', to='questify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_nilai', models.IntegerField()),
                ('waktu_pengajaran', models.DateTimeField(auto_now_add=True)),
                ('tanggal_percobaan', models.DateTimeField(auto_now_add=True)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='questify_app.modulpembelajaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='questify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan_user', models.CharField(max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('waktu_jawab', models.DateTimeField(auto_now_add=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_user', to='questify_app.soal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_user', to='questify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=255)),
                ('nama_belakang', models.CharField(max_length=255)),
                ('foto', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_user', to='questify_app.user')),
            ],
        ),
    ]
