# Generated by Django 5.1.3 on 2024-11-19 13:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_metode', models.CharField(max_length=50)),
                ('no_rek', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riwayatpembelian',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='riwayatpembelian',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeUser',
        ),
        migrations.AlterField(
            model_name='jawabanuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='deskripsi',
            new_name='deskripsi_1',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='kelas',
            name='deskripsi_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modulpembelajaran',
            name='kategori',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='batas_waktu_pembayaran',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('gagal', 'Gagal'), ('berhasil', 'Berhasil')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='questify_app.metodepembayaran'),
        ),
        migrations.DeleteModel(
            name='DetailUser',
        ),
        migrations.DeleteModel(
            name='RiwayatPembelian',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
