# Generated by Django 5.1.3 on 2024-11-06 14:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_metode', models.CharField(max_length=50)),
                ('no_rek', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='batas_waktu_pembayaran',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('gagal', 'Gagal'), ('berhasil', 'Berhasil')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='questify_app.metodepembayaran'),
        ),
        migrations.DeleteModel(
            name='RiwayatPembelian',
        ),
    ]
