# Generated by Django 5.1.3 on 2024-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0002_contactmessage_metodepembayaran_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulpembelajaran',
            name='gratis',
            field=models.BooleanField(default=True),
        ),
    ]
