# Generated by Django 5.1.3 on 2024-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0003_modulpembelajaran_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='jumlah_soal',
            field=models.IntegerField(default=0),
        ),
    ]
