# Generated by Django 5.1.3 on 2024-11-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0004_remove_transaksi_total_pembayaran_transaksi_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='link_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
