# Generated by Django 5.1.3 on 2024-11-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0004_alter_modulpembelajaran_jumlah_soal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'ordering': ['user', 'modul', 'percobaan_ke']},
        ),
        migrations.AddField(
            model_name='jawabanuser',
            name='percobaan_ke',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nilai',
            name='percobaan_ke',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jawabanuser',
            name='pilihan_user',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_user', to='questify_app.modulpembelajaran'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='waktu_pengajaran',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='soal',
            name='nilai_jawaban',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='soal',
            name='pilihan_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='pilihan_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='pilihan_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='pilihan_d',
            field=models.CharField(max_length=200),
        ),
    ]
