# Generated by Django 5.1.3 on 2024-11-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0005_user_detailuser_alter_jawabanuser_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
