# Generated by Django 5.1.3 on 2024-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0005_alter_nilai_options_jawabanuser_percobaan_ke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='soal_gambar/'),
        ),
    ]
