# Generated by Django 5.1.3 on 2024-11-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
