# Generated by Django 5.1.3 on 2024-11-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0007_remove_modulpembelajaran_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulpembelajaran',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulpembelajaran',
            name='jumlah_soal',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='gratis',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='kategori',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul_pembelajaran', to='questify_app.kelas'),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='waktu_pengajaran',
            field=models.IntegerField(),
        ),
    ]
