# Generated by Django 5.1.3 on 2024-11-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0008_modulpembelajaran_deskripsi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='jumlah_soal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soal',
            name='nilai_jawaban',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percobaan_ke', models.IntegerField(default=1)),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questify_app.soal')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questify_app.modulpembelajaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'modul')},
            },
        ),
    ]
