# Generated by Django 5.1.3 on 2024-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0009_alter_modulpembelajaran_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulpembelajaran',
            name='deskripsi',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
