# Generated by Django 5.1.3 on 2024-11-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0010_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
