# Generated by Django 5.1.3 on 2024-11-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0011_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeUser',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jawabanuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DetailUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
