# Generated by Django 5.1.3 on 2024-12-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0007_delete_user'),
        ('questify_app', '0011_percobaanterakhir'),
    ]

    operations = [
    ]
