# Generated by Django 5.1.3 on 2024-11-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0013_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='deskripsi',
            new_name='deskripsi_1',
        ),
        migrations.AddField(
            model_name='kelas',
            name='deskripsi_2',
            field=models.TextField(default=''),
        ),
    ]
