# Generated by Django 5.1.3 on 2024-12-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0013_skor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skor',
        ),
    ]
