# Generated by Django 5.1.3 on 2024-12-06 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0014_delete_skor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='tanggal_transaksi',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='batas_waktu_pembayaran',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='metode_pembayaran',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='status_pembayaran',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questify_app.kelas'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='link_payment',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
