# Generated by Django 5.1.3 on 2024-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0016_rename_created_at_transaksi_tanggal_transaksi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
