# Generated by Django 5.1.3 on 2024-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0017_alter_transaksi_status_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
