# Generated by Django 5.1.3 on 2024-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0018_transaksi_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='settlement', max_length=10),
        ),
    ]
