# Generated by Django 5.1.3 on 2024-12-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0020_transaksi_tanggal_berakhir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='tanggal_berakhir',
        ),
    ]
