# Generated by Django 5.1.3 on 2024-12-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0022_remove_transaksi_metode_pembayaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_metode', models.CharField(max_length=50)),
                ('no_rek', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='questify_app.metodepembayaran'),
        ),
    ]
