# Generated by Django 5.1.3 on 2024-12-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0023_metodepembayaran_transaksi_metode_pembayaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='metode_pembayaran',
        ),
        migrations.DeleteModel(
            name='MetodePembayaran',
        ),
    ]
