# Generated by Django 5.1.3 on 2024-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0024_remove_transaksi_metode_pembayaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pencapaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('skor_minimum', models.PositiveIntegerField()),
                ('gambar', models.ImageField(upload_to='pencapaian/')),
            ],
        ),
    ]
