# Generated by Django 5.1.3 on 2024-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questify_app', '0025_pencapaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(max_length=10),
        ),
    ]
